content/api-reference/mutations/mark-message-as-read.mdx
content/api-reference/mutations/submit-checklist-response.mdx
content/api-reference/mutations/submit-form-response.mdx
content/api-reference/queries/get-api-call.mdx
content/api-reference/queries/get-checklist.mdx
content/api-reference/queries/get-emr-report.mdx
content/api-reference/queries/get-form.mdx
content/api-reference/queries/get-message.mdx
content/api-reference/queries/search-patient.mdx

Changes: 
- Add "X-User-ID" header info to reference docs for mutations that require it
- Add component/activity id examples to relevant activity queries

Add X-User-ID details and activity/component id examples

---

content/api-reference/queries/search-activities.mdx

https://awellhealth.atlassian.net/browse/AST-3196

AST-3196: pagination & sorting documentation for "activities" query

---

content/api-reference/queries/get-pathway.mdx

https://awellhealth.atlassian.net/browse/AST-3167

AST-3167: updated docs for pathway query

---

content/api-reference/queries/get-data-point-definitions.mdx
src/config/menus/apiMenu.ts

https://awellhealth.atlassian.net/browse/AST-3161

AST-3161: new docs for pathwaydatapointdefinitions query

---

content/api-reference/queries/get-patient-pathways.mdx

- https://awellhealth.atlassian.net/browse/AST-3169
- https://awellhealth.atlassian.net/browse/AST-3210
- https://awellhealth.atlassian.net/browse/AST-3209
- https://awellhealth.atlassian.net/browse/AST-3208

AST-3169: updated docs for patientPathways query

---

content/api-reference/queries/get-data-point-definitions.mdx

Missing range, unit and optional fields

Missing range, unit and optional fields

---

content/api-reference/queries/get-published-pathways.mdx

Missing release_id in publishedPathwayDefinitions

Missing release_id in publishedPathwayDefinitions

---

content/api-reference/queries/get-pathway-elements.mdx
src/config/menus/apiMenu.ts
src/types/generated/api.types.ts
styles/components/docStyles.css

docs(pathwayelements): document query

---

src/config/menus/apiMenu.ts

Reverts nckhell/awell-developers#32

Revert "fix: fix broken complete checklist link in menu"

---

.gitignore
content/api-reference/mutations/submit-checklist-response.mdx
content/api-reference/mutations/submit-form-response.mdx
src/config/menus/apiMenu.ts

Changes:
- rename to 'submit checklist response' for consistency, revert menu change
- update descriptions for submit checklist and form pages
- add .dccache to .gitignore

Fix checklist link and misc updates

---

content/api-reference/mutations/resend-emr-report.mdx
content/changelog/1_15_4.mdx
content/changelog/1_15_x.mdx
src/config/menus/apiMenu.ts

https://awellhealth.atlassian.net/browse/AST-3561
**To do:**
Add the correct release number as soon as it's known.

AST-3561: retryPushToEmr mutation

---

content/awell-orchestration/docs/getting-started/integrations-overview.mdx

The image is hidden, the src should be replaced with chosen image and "display:none" should be removed right after

Updated overview options list

---

content/awell-orchestration/api-reference/queries/get-form.mdx
content/awell-orchestration/api-reference/queries/get-forms-in-pathway.mdx
content/awell-orchestration/developer-tools/changelog/1_18_3.mdx
src/config/menus/awell-orchestration/apiMenu.ts

Reference: [AST-4156](https://awellhealth.atlassian.net/browse/AST-4156) and [AST-4226](https://awellhealth.atlassian.net/browse/AST-4226)

Update developer docs for v1.18.3 release

---

content/awell-orchestration/api-reference/queries/get-pathways.mdx
content/awell-orchestration/api-reference/queries/get-patients.mdx
content/awell-orchestration/api-reference/queries/search-activities.mdx
content/awell-orchestration/developer-tools/changelog/1_20_6.mdx

Changes:
- add search filter details to `get patients` query
- update details of pagination and sorting for `get patients`, `search activities`, `get pathways`

docs(queries): update filter, pagination and sorting details for assorted queries

---

content/awell-orchestration/api-reference/mutations/start-hosted-activity-session.mdx
content/awell-orchestration/api-reference/mutations/start-hosted-pathway-session.mdx

…in startHostedPathwaySession mutation

update(orchestration): change success_url and cancel_url to optional 

---

content/awell-orchestration/developer-tools/webhooks/security.mdx

- explain what key is used and what's used as input
- include typescript code sample for signature verification
AST-5020

feat(webhooks): add explanation and code sample for webhook signature

---

content/awell-extensions/docs/getting-started/contributing-guidelines.mdx

48 hrs/72 hrs/1 wk for sm/md/lg PRs

added an SLA for PRs to set expectations

---

content/awell-orchestration/docs/data/kibana/introduction.mdx
content/awell-orchestration/docs/going-live/sandbox-to-production-promotion-guide.mdx
content/faq.mdx
pages/request-promotion.tsx

Changes:
- add references to UK production environment in various pages

docs(): add missing production UK environment references

---

content/awell-orchestration/api-reference/mutations/schedule-track.mdx
content/awell-orchestration/api-reference/mutations/unschedule-tracks.mdx
content/awell-orchestration/api-reference/queries/get-scheduled-tracks.mdx
src/config/menus/awell-orchestration/apiMenu.ts
src/types/generated/api.types.ts

Changes:
- get scheduled tracks
- unschedule tracks
- schedule track

docs(awell-orchestration): add docs for scheduling tracks

---

content/awell-orchestration/docs/going-live/preflight-checklist.mdx

Including updates to extensions and new mechanisms to publish & set care flows live.

[Change Management] Publish and Set Live Updates

---

content/awell-orchestration/docs/trigger-care-flows/trigger-types/incoming-webhooks.mdx
src/types/generated/api.types.ts

Screenshots I would like to include:

V1C-384-Update-incoming-webhooks-documentation

---

content/awell-orchestration/api-reference/queries/get-pathway-activities.mdx
content/awell-studio/docs/getting-started/design-ontology.mdx
content/awell-studio/docs/source-control/concepts/components.mdx

Add part on sorting and default number returned.

TP-2258-update-activity-query-documentation-to-include-pagination

---

content/awell-extensions/docs/custom-actions/development/on-activity-created.mdx
content/awell-extensions/docs/custom-actions/development/on-event.mdx
src/config/menus/awell-extensions/docsMenu.ts

deprecate the onActivityCreated page; add the onEvent page

onEvent page

---

content/awell-orchestration/api-reference/queries/get-pathway-data-points.mdx
src/config/menus/awell-orchestration/apiMenu.ts

adds query for pathway data points

pathway data points
